/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry.toml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Registry manifest (public)
         * @description The auth-free CLI registry manifest.
         */
        get: operations["getRegistryToml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog (public)
         * @description The auth-free pack catalog.
         */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session/token identity
         * @description Session, Registry-native gcr_ bearer, or Gasworks STS EIA.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/device/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start device grant (public)
         * @description RFC 8628.
         */
        post: operations["deviceCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/device/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll device grant (public)
         * @description Returns a gcr_ token when approved, else an OAuth pending/denied error.
         */
        post: operations["deviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/device/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a device code
         * @description Session + CSRF.
         */
        post: operations["deviceApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/device/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deny a device code
         * @description Session + CSRF.
         */
        post: operations["deviceDeny"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cli/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a CLI token
         * @description Session + CSRF → gcr_ personal token.
         */
        post: operations["mintCliToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish-tokens/github-actions/mint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a GitHub-Actions publish token
         * @description GitHub OIDC (audience gascity-registry) → short-lived gcr_ token.
         */
        post: operations["mintGithubActionsToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API tokens
         * @description Session + CSRF.
         */
        get: operations["listApiTokens"];
        put?: never;
        /**
         * Create an API token
         * @description Session + CSRF.
         */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/api-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API token
         * @description Session + CSRF.
         */
        delete: operations["revokeApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pack ownership (public)
         * @description Query packKey/sourceUrl.
         */
        get: operations["getOwnership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GitHub webhook (HMAC)
         * @description x-hub-signature-256 verified.
         */
        post: operations["githubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a publish request
         * @description Registry-native gcr_ bearer, Gasworks STS EIA, or session+CSRF. With ?validate=1, validation runs synchronously after the request is durably created.
         */
        post: operations["createPublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/publish-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my publish-request feedback
         * @description Browser session or personal Registry bearer token. GitHub Actions publish tokens are denied.
         */
        get: operations["listMyPublishRequestFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/publish-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my publish-request feedback */
        get: operations["getMyPublishRequestFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/publish-requests/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a submitter comment
         * @description Browser session plus CSRF, or personal Registry bearer token. Only non-terminal requests may be commented on.
         */
        post: operations["commentOnMyPublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/publish-requests/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a publish request read
         * @description Browser session plus CSRF, or personal Registry bearer token. The unread version is cleared only when observedUnreadAt exactly matches.
         */
        post: operations["markMyPublishRequestRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publish-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a staff publish-request conversation
         * @description Administrator or moderator browser session only; no CSRF is required for this safe read.
         */
        get: operations["getAdminPublishRequestFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publish-requests/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a staff publish-request comment
         * @description Administrator or moderator browser session plus CSRF only.
         */
        post: operations["commentOnAdminPublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/publish-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My publish requests
         * @description Session + CSRF.
         */
        get: operations["listMyPublishRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish-requests/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revalidate a publish request
         * @description Session + CSRF. The submitter or registry staff may rerun validation on a non-terminal request.
         */
        post: operations["validatePublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a publish request
         * @description Session + CSRF + staff. Runs the merge gate: validated, source-repository control, the namespace rules (unscoped names are reserved; a scoped name's scope must be the proven repository owner; the name's existing claim must point at the source repository), the withdrawn-version guard, and an aggregate dry run.
         */
        post: operations["approvePublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a publish request
         * @description Session + CSRF + staff.
         */
        post: operations["rejectPublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publish-requests/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw (take down) an approved publish
         * @description Session + CSRF + staff. Only an approved request can be withdrawn; the release drops from the served catalog and the row becomes terminal.
         */
        post: operations["withdrawPublishRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reviews (public)
         * @description Query packKey.
         */
        get: operations["listReviews"];
        /**
         * Create/update a review
         * @description Session + CSRF.
         */
        put: operations["upsertReview"];
        post?: never;
        /**
         * Delete a review
         * @description Session + CSRF; query packKey.
         */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My reviews
         * @description Session + CSRF.
         */
        get: operations["listMyReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle a star
         * @description Session + CSRF.
         */
        put: operations["toggleStar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicUser: {
            id: string;
            handle: string;
            displayName: string;
            avatarUrl?: string;
            email?: string;
            /** @enum {string} */
            role: "admin" | "moderator" | "user";
        };
        Me: {
            user?: components["schemas"]["PublicUser"] | null;
            csrfToken?: string | null;
            authConfigured: boolean;
            authProvider?: string | null;
            devAuthEnabled: boolean;
            /** @enum {string} */
            store: "file" | "postgres";
        };
        PublishRegistryRelease: {
            version: string;
            ref: string;
            commit: string;
            hash: string;
            description: string;
        };
        PublishRegistryEntry: {
            name: string;
            description: string;
            source: string;
            /** @enum {string} */
            sourceKind: "git";
            release: components["schemas"]["PublishRegistryRelease"];
        };
        /** @enum {string} */
        PublishRequestStatus: "pending_validation" | "validation_failed" | "pending_review" | "approved" | "rejected" | "withdrawn";
        /** @enum {string} */
        PublishRequestActionOwner: "submitter" | "registry";
        /** @enum {string} */
        PublishRequestNextStep: "await_validation" | "fix_validation" | "respond_to_feedback" | "await_registry_review" | "published" | "resubmit";
        PublishRequestComment: {
            id: string;
            authorHandle: string;
            authorRole: components["schemas"]["PublishRequestActionOwner"];
            /** @description Plain text only; clients must not render it as HTML. */
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Fields shared by owner summaries and staff detail. */
        PublishRequestFeedbackCoreSummary: {
            id: string;
            status: components["schemas"]["PublishRequestStatus"];
            nextStep: components["schemas"]["PublishRequestNextStep"];
            actionRequiredBy?: components["schemas"]["PublishRequestActionOwner"];
            requestedName: string;
            requestedVersion: string;
            repository: {
                /** @enum {string} */
                host: "github.com";
                owner: string;
                name: string;
                fullName: string;
            };
            packPath: string;
            commit: string;
            statusReason?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Owner-facing summary. The unread version timestamps let the owner acknowledge exactly the update they observed. */
        PublishRequestFeedbackSummary: components["schemas"]["PublishRequestFeedbackCoreSummary"] & {
            unread: boolean;
            /** Format: date-time */
            submitterUnreadAt: string | null;
        };
        PublishRequestFeedbackDetailFields: {
            repoUrl: string;
            sourceUrl: string;
            requestedRef?: string;
            requestedDescription?: string;
            validationError?: string;
            /** Format: date-time */
            validatedAt?: string;
            /** Format: date-time */
            reviewedAt?: string;
            registryEntry?: components["schemas"]["PublishRegistryEntry"];
            comments: components["schemas"]["PublishRequestComment"][];
        };
        PublishRequestFeedbackDetail: components["schemas"]["PublishRequestFeedbackSummary"] & components["schemas"]["PublishRequestFeedbackDetailFields"];
        /** @description Staff detail snapshot. Submitter unread/read state is private and is not part of this schema. */
        StaffPublishRequestFeedbackDetail: components["schemas"]["PublishRequestFeedbackCoreSummary"] & components["schemas"]["PublishRequestFeedbackDetailFields"] & {
            submittedBy: components["schemas"]["PublicUser"];
        };
        PublishRequestFeedbackListResponse: {
            publishRequests: components["schemas"]["PublishRequestFeedbackSummary"][];
            unreadCount: number;
        };
        PublishRequestFeedbackDetailResponse: {
            publishRequest: components["schemas"]["PublishRequestFeedbackDetail"];
        };
        AdminPublishRequestFeedbackDetailResponse: {
            publishRequest: components["schemas"]["StaffPublishRequestFeedbackDetail"];
        };
        PublishRequestCommentInput: {
            body: string;
        };
        StaffPublishRequestCommentInput: components["schemas"]["PublishRequestCommentInput"] & {
            actionRequiredBy: components["schemas"]["PublishRequestActionOwner"];
        };
        PublishRequestCommentMutationResponse: {
            comment: components["schemas"]["PublishRequestComment"];
        };
        PublishRequestReadInput: {
            /** Format: date-time */
            observedUnreadAt: string;
        };
        PublishRequest: {
            id: string;
            /** @enum {string} */
            status: "pending_validation" | "validation_failed" | "pending_review" | "approved" | "rejected" | "withdrawn";
            repoUrl?: string;
            sourceUrl?: string;
            packPath?: string;
            commit?: string;
            requestedName: string;
            requestedVersion: string;
            requestedDescription?: string;
            registryEntry?: components["schemas"]["PublishRegistryEntry"];
            validationError?: string;
            statusReason?: string;
            /** @enum {string} */
            submissionMethod?: "web_session" | "api_token" | "github_actions_oidc" | "github_import";
            /** @description Rename-stable GitHub repository ID recorded by a repo-proven submission. */
            sourceGithubRepositoryId?: string;
            /** @description Rename-stable GitHub owner ID recorded by a repo-proven submission. */
            sourceGithubOwnerId?: string;
            createdAt: string;
            updatedAt: string;
        } & {
            [key: string]: unknown;
        };
        PublishRequestResponse: {
            publishRequest: components["schemas"]["PublishRequest"];
        };
        PublishValidationErrorResponse: components["schemas"]["ApiError"] & {
            publishRequest: components["schemas"]["PublishRequest"];
        };
        PublishRequestInput: {
            repoUrl: string;
            commit: string;
            packPath?: string;
            requestedName: string;
            requestedVersion: string;
            requestedRef?: string;
            requestedDescription?: string;
        };
        ApiTokenRow: {
            id: string;
            label: string;
            prefix: string;
            /** @enum {string} */
            kind: "personal" | "github_actions_publish";
            createdAt: string;
            expiresAt?: string;
            lastUsedAt?: string;
            revokedAt?: string;
        };
        ApiTokenCreateResult: components["schemas"]["ApiTokenRow"] & {
            /** @description shown once */
            token: string;
        };
        ReviewRow: {
            id: string;
            packKey: string;
            rating: number;
            title?: string;
            body: string;
            recommend: boolean;
            createdAt: string;
            updatedAt: string;
            user: components["schemas"]["PublicUser"];
            viewerCanDelete: boolean;
        };
        ReviewListResult: {
            summary: {
                count: number;
                averageRating?: number | null;
                recommendCount: number;
            };
            reviews: components["schemas"]["ReviewRow"][];
            viewerReview?: components["schemas"]["ReviewRow"] | null;
            viewerHasStarred: boolean;
        };
        DeviceCodeResponse: {
            device_code: string;
            user_code: string;
            verification_uri: string;
            verification_uri_complete: string;
            expires_in: number;
            interval: number;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "bearer";
            scope: string;
            registry_url?: string;
            audience?: string;
            expires_at?: string;
        };
        OAuthError: {
            /** @enum {string} */
            error: "authorization_pending" | "access_denied" | "expired_token" | "slow_down";
        } & {
            [key: string]: unknown;
        };
        ApiError: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getRegistryToml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TOML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    deviceCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCodeResponse"];
                };
            };
        };
    };
    deviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Pending/denied. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
        };
    };
    deviceApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deviceDeny: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    mintCliToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreateResult"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    mintGithubActionsToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listApiTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenRow"][];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreateResult"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    revokeApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    githubWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad signature. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createPublishRequest: {
        parameters: {
            query?: {
                /** @description Set to 1 or true to validate the durable request before responding. */
                validate?: "1" | "true";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequestInput"];
            };
        };
        responses: {
            /** @description Created. A synchronous validation success is wrapped as { publishRequest }; creation without validation returns the request directly. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequest"] | components["schemas"]["PublishRequestResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Invalid create input, or synchronous validation failed after creation. The latter includes both the machine-readable error and the durable validation_failed request. Validation judges the NAME as well as the contents: `PUBLISH_NAME_RESERVED` (unscoped pack names are reserved unless the registry already holds a claim for that name) and `PUBLISH_SCOPE_MISMATCH` (a scoped name's scope must equal the source repository's owner, case-folded) are refused here, before pack.toml is fetched. Both codes also appear as 403 on the approve route, which re-checks the same rule against live claim state; clients keying on `error.code` need no change, clients keying on (status, code) pairs must accept both. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"] | components["schemas"]["PublishValidationErrorResponse"];
                };
            };
            /** @description Synchronous validation failed unexpectedly after the request was durably created. The response includes the validation_failed request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishValidationErrorResponse"];
                };
            };
            /** @description The validator produced an unusable pack hash after the request was durably created (`BAD_GC_HASH`). The response includes the validation_failed request. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishValidationErrorResponse"];
                };
            };
        };
    };
    listMyPublishRequestFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequestFeedbackListResponse"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Token scope denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Per-user feedback read limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMyPublishRequestFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequestFeedbackDetailResponse"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Token scope denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or non-owned request. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Per-user feedback read limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    commentOnMyPublishRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequestCommentInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequestCommentMutationResponse"];
                };
            };
            /** @description Malformed JSON body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description CSRF validation or token scope denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or non-owned request. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `REQUEST_TERMINAL` when the request is no longer mutable, or `STATE_CONFLICT` when its state changes during the atomic mutation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description JSON body exceeds the transport byte limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Comment is empty, contains an unsupported character, or exceeds 4,000 Unicode characters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Per-user feedback mutation limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    markMyPublishRequestRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequestReadInput"];
            };
        };
        responses: {
            /** @description Acknowledged. A stale or fabricated version is an idempotent no-op. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed JSON body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description CSRF validation or token scope denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or non-owned request. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description JSON body exceeds the transport byte limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Invalid timestamp. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Per-user feedback mutation limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAdminPublishRequestFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. Submitter unread/read timestamps are intentionally omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPublishRequestFeedbackDetailResponse"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Staff role required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Per-user feedback read limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    commentOnAdminPublishRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffPublishRequestCommentInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequestCommentMutationResponse"];
                };
            };
            /** @description Malformed JSON body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Staff role or CSRF validation failed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `REQUEST_TERMINAL` when the request is no longer mutable, or `STATE_CONFLICT` when its state changes during the atomic mutation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description JSON body exceeds the transport byte limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Comment/action owner is invalid or the comment exceeds 4,000 Unicode characters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Per-user feedback mutation limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyPublishRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        publishRequests: components["schemas"]["PublishRequest"][];
                    };
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    validatePublishRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation passed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequestResponse"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request belongs to another publisher. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Publish request not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request is approved, rejected, or withdrawn and cannot re-enter validation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation failed. The response includes both the machine-readable error and the durable validation_failed request. Namespace policy is checked first, so `PUBLISH_NAME_RESERVED` (unscoped pack names are reserved unless the registry already holds a claim for that name) and `PUBLISH_SCOPE_MISMATCH` (a scoped name's scope must equal the source repository's owner, case-folded) are refused here — including for queued rows that predate the check, which fail their next validation with the rename instruction. Both codes also appear as 403 on the approve route, which re-checks the same rule against live claim state. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishValidationErrorResponse"];
                };
            };
            /** @description Validation failed unexpectedly. The response includes the durable validation_failed request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishValidationErrorResponse"];
                };
            };
            /** @description The validator produced an unusable pack hash (`BAD_GC_HASH`). The response includes the durable validation_failed request. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishValidationErrorResponse"];
                };
            };
        };
    };
    approvePublishRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Audited justification for approving a claim-only publish with no proof of source-repository control. Does NOT authorize re-pinning a pack name. */
                    ownershipOverrideReason?: string;
                    /** @description Audited justification for re-pointing an existing pack-name claim at this request's repository (the repository-migration path). Recorded with both the previous and the new binding. */
                    namePinOverrideReason?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequest"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. `FORBIDDEN` (not staff), `OWNERSHIP_NOT_VERIFIED` (no proof of source-repository control), `PUBLISH_NAME_RESERVED` (unscoped pack names are reserved for ingested packs and cannot be minted by a publish), or `PUBLISH_SCOPE_MISMATCH` (the name's scope is not the source repository's owner). The two name codes have no staff override. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict. `PUBLISH_NAME_OWNER_MISMATCH` (the pack name is claimed by another repository; a `namePinOverrideReason` re-pins it instead), `PUBLISH_VERSION_WITHDRAWN` (this lineage's name@version was withdrawn and can only be reinstated with identical commit, hash and ref), `PUBLISH_CONFLICT` (the approval would not merge into the served catalog), or `CONFLICT` (the name's claim changed while this approval was in review — a concurrent approval or claim release won the race; re-open the request and approve again). `CONFLICT` is a retry, NOT a re-pin: the claim is authoritative and the request was not merged. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable. `PUBLISH_NOT_VALIDATED` (the request must be validated before approval) or `VALIDATION_ERROR` (an override reason is too long). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    rejectPublishRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequest"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    withdrawPublishRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Audited takedown reason. */
                    reason?: string;
                    /** @description Also unclaim the pack name, in the same transaction as the takedown. Off by default: a content takedown must leave the name pinned to the repository that owns it. Releasing an unscoped name does not make it publishable again — unscoped names stay reserved. */
                    releaseNameClaim?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishRequest"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable. `VALIDATION_ERROR` when `releaseNameClaim` cannot be honoured: the name is unscoped (bare names stay reserved, so releasing the claim would make the name permanently unpublishable), or another approved release of the same name is still served (releasing would unclaim a live name, and the next boot's grandfather backfill would silently re-mint the claim against the first-approved repo). Nothing is withdrawn when the release is refused. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResult"];
                };
            };
        };
    };
    upsertReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRow"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRow"][];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    toggleStar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
